#FROM nginx
#COPY 441Clients /usr/share/nginx/html
#EXPOSE 443
#ADD default.conf /etc/nginx/conf.d/default.conf

# use `node` image as the base
#FROM node
# set the current working directory to /app
#WORKDIR /app
# copy the package.json and package-lock.json files to the work directory
#COPY package.json package-lock.json ./
#COPY package.json package-lock.json /app/
# run npm install to install all dependent packages
#RUN npm install
# copy your JavaScript source files
#COPY . .
#COPY . /app
# declare that your server will listen on port 80
#EXPOSE 80
# set the entrypoint command
#ENTRYPOINT ["node", "src/index.js"]